<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function follows(){
        return $this->belongsToMany(User::class,'follows','user_id','follow_id');
    }

    public function follow(User $user){
        $this->follows()->toggle($user);
    }
    public function following(User $user){
        return $this->follows()->contains($user);
    }
    public function getRouteKeyName()
    {
        return "username"; // TODO: Change the autogenerated stub
    }

}
